// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrIwyrIriYPNiLgyNtJsfk6PYUzXHrCZY',
    appId: '1:428827826455:web:4265d8a8c247f6a189bf52',
    messagingSenderId: '428827826455',
    projectId: 'auth-app-b8482',
    authDomain: 'auth-app-b8482.firebaseapp.com',
    storageBucket: 'auth-app-b8482.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8leqN-6TQC7WFbufnD78AZsD5rNCyNvo',
    appId: '1:428827826455:android:f83e5d404206655889bf52',
    messagingSenderId: '428827826455',
    projectId: 'auth-app-b8482',
    storageBucket: 'auth-app-b8482.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBnKvJOcc53ny8doPYS5yyKf77IK4uezI',
    appId: '1:428827826455:ios:25fd4c3ad39d520489bf52',
    messagingSenderId: '428827826455',
    projectId: 'auth-app-b8482',
    storageBucket: 'auth-app-b8482.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBnKvJOcc53ny8doPYS5yyKf77IK4uezI',
    appId: '1:428827826455:ios:25fd4c3ad39d520489bf52',
    messagingSenderId: '428827826455',
    projectId: 'auth-app-b8482',
    storageBucket: 'auth-app-b8482.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrIwyrIriYPNiLgyNtJsfk6PYUzXHrCZY',
    appId: '1:428827826455:web:7bf7b62e0903beb189bf52',
    messagingSenderId: '428827826455',
    projectId: 'auth-app-b8482',
    authDomain: 'auth-app-b8482.firebaseapp.com',
    storageBucket: 'auth-app-b8482.firebasestorage.app',
  );
}
